import { Book } from './types';

export const HIGH_REPUBLIC_DATA: Book[] = [
  { id: 'p1-light-of-the-jedi', title: 'Light of the Jedi', phase: 'Phase 1', format: 'Adult Novel', read: false },
  { id: 'p1-starlight-go-together', title: 'Starlight: Go Together', phase: 'Phase 1', format: 'Short Story', read: false },
  { id: 'p1-into-the-dark', title: 'Into the Dark', phase: 'Phase 1', format: 'YA Novel', read: false },
  { id: 'p1-a-test-of-courage', title: 'A Test of Courage', phase: 'Phase 1', format: 'Middle Grade', read: false },
  { id: 'p1-sw-adventures-6', title: 'SW Adventures (2020) #6 - The Gaze Electric', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-vol-1', title: 'High Republic Adventures (2021) Vol. 1', phase: 'Phase 1', format: 'Comic (TPB)', read: false },
  { id: 'p1-starlight-first-duty', title: 'Starlight: First Duty', phase: 'Phase 1', format: 'Short Story', read: false },
  { id: 'p1-thr-vol-1', title: 'THR (2021) Vol. 1: There is No Fear', phase: 'Phase 1', format: 'Comic (TPB)', read: false },
  { id: 'p1-starlight-hidden-danger', title: 'Starlight: Hidden Danger', phase: 'Phase 1', format: 'Short Story', read: false },
  { id: 'p1-the-rising-storm', title: 'The Rising Storm', phase: 'Phase 1', format: 'Adult Novel', read: false },
  { id: 'p1-race-to-crashpoint-tower', title: 'Race To Crashpoint Tower', phase: 'Phase 1', format: 'Middle Grade', read: false },
  { id: 'p1-hra-06', title: 'High Republic Adventures (2021) #06', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-07', title: 'High Republic Adventures (2021) #07', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-fcbd-2021', title: 'HRA Free Comic Book Day 2021', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-monster-of-temple-peak', title: 'The Monster of Temple Peak', phase: 'Phase 1', format: 'Comic (TPB)', read: false },
  { id: 'p1-thr-06', title: 'The High Republic (2021) #06', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-thr-07', title: 'The High Republic (2021) #07', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-thr-08', title: 'The High Republic (2021) #08', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-starlight-past-mistakes', title: 'Starlight: Past Mistakes', phase: 'Phase 1', format: 'Short Story', read: false },
  { id: 'p1-edge-of-balance-vol-1', title: 'The Edge Of Balance Vol. 1', phase: 'Phase 1', format: 'Manga', read: false },
  { id: 'p1-out-of-the-shadows', title: 'Out Of The Shadows', phase: 'Phase 1', format: 'YA Novel', read: false },
  { id: 'p1-hra-08', title: 'High Republic Adventures (2021) #08', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-09', title: 'High Republic Adventures (2021) #09', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-10', title: 'High Republic Adventures (2021) #10', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-tempest-runner', title: 'Tempest Runner', phase: 'Phase 1', format: 'Audio Drama', read: false },
  { id: 'p1-thr-09', title: 'The High Republic (2021) #09', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-thr-10', title: 'The High Republic (2021) #10', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-thr-11', title: 'The High Republic (2021) #11', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-annual-2021', title: 'HRA Annual 2021', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-trail-of-shadows-1', title: 'Trail of Shadows #1', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-trail-of-shadows-2', title: 'Trail of Shadows #2', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-mission-to-disaster', title: 'Mission to Disaster', phase: 'Phase 1', format: 'Middle Grade', read: false },
  { id: 'p1-hra-bake-off', title: 'HRA: Galactic Bake-Off Spectacular', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-11', title: 'High Republic Adventures (2021) #11', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-trail-of-shadows-3', title: 'Trail of Shadows #3', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-thr-12', title: 'The High Republic (2021) #12', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-starlight-shadows-remain', title: 'Starlight: Shadows Remain', phase: 'Phase 1', format: 'Short Story', read: false },
  { id: 'p1-sw-adventures-14', title: 'SW Adventures (2020) #14 - A Nihil Interlude', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-fallen-star', title: 'The Fallen Star', phase: 'Phase 1', format: 'Adult Novel', read: false },
  { id: 'p1-thr-13', title: 'The High Republic (2021) #13', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-thr-14', title: 'The High Republic (2021) #14', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-thr-15', title: 'The High Republic (2021) #15', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-12', title: 'High Republic Adventures (2021) #12', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-13', title: 'High Republic Adventures (2021) #13', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-midnight-horizon', title: 'Midnight Horizon', phase: 'Phase 1', format: 'YA Novel', read: false },
  { id: 'p1-edge-of-balance-vol-2', title: 'The Edge of Balance, Vol. 2', phase: 'Phase 1', format: 'Manga', read: false },
  { id: 'p1-trail-of-shadows-4', title: 'Trail of Shadows #4', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-trail-of-shadows-5', title: 'Trail of Shadows #5', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-hra-fcbd-2023', title: 'HRA Free Comic Book Day 2023', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-eye-of-the-storm-1', title: 'Eye of the Storm #1', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p1-eye-of-the-storm-2', title: 'Eye of the Storm #2', phase: 'Phase 1', format: 'Comic', read: false },
  { id: 'p2-path-of-deceit', title: 'Path of Deceit', phase: 'Phase 2', format: 'YA Novel', read: false },
  { id: 'p2-convergence', title: 'Convergence', phase: 'Phase 2', format: 'Adult Novel', read: false },
  { id: 'p2-quest-hidden-city', title: 'Quest for the Hidden City', phase: 'Phase 2', format: 'Middle Grade', read: false },
  { id: 'p2-the-blade', title: 'The Blade', phase: 'Phase 2', format: 'Comic (TPB)', read: false },
  { id: 'p2-toe-new-prospects', title: 'Tales Of Enlightenment: New Prospects', phase: 'Phase 2', format: 'Short Story', read: false },
  { id: 'p2-toe-different-perspective', title: 'Tales Of Enlightenment: A Different Perspective', phase: 'Phase 2', format: 'Short Story', read: false },
  { id: 'p2-thr-01', title: 'The High Republic (2022) #01', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-thr-02', title: 'The High Republic (2022) #02', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-thr-03', title: 'The High Republic (2022) #03', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-hra-vol-1', title: 'HRA (2022): Volume 1', phase: 'Phase 2', format: 'Comic (TPB)', read: false },
  { id: 'p2-battle-of-jedha', title: 'The Battle of Jedha', phase: 'Phase 2', format: 'Audio Drama', read: false },
  { id: 'p2-thr-04', title: 'The High Republic (2022) #04', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-thr-05', title: 'The High Republic (2022) #05', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-thr-06', title: 'The High Republic (2022) #06', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-thr-07', title: 'The High Republic (2022) #07', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-thr-08', title: 'The High Republic (2022) #08', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-hra-vol-2', title: 'HRA (2022): Volume 2', phase: 'Phase 2', format: 'Comic (TPB)', read: false },
  { id: 'p2-toe-unusual-suspect', title: 'Tales Of Enlightenment: The Unusual Suspect', phase: 'Phase 2', format: 'Short Story', read: false },
  { id: 'p2-toe-no-such-thing', title: 'Tales Of Enlightenment: No Such Thing...', phase: 'Phase 2', format: 'Short Story', read: false },
  { id: 'p2-toe-last-orders', title: 'Tales of Enlightenment: Last Orders', phase: 'Phase 2', format: 'Short Story', read: false },
  { id: 'p2-cataclysm', title: 'Cataclysm', phase: 'Phase 2', format: 'Adult Novel', read: false },
  { id: 'p2-hra-nameless-terror', title: 'HRA: The Nameless Terror', phase: 'Phase 2', format: 'Comic (TPB)', read: false },
  { id: 'p2-quest-planet-x', title: 'Quest for Planet X', phase: 'Phase 2', format: 'Middle Grade', read: false },
  { id: 'p2-hra-quest-jedi', title: 'HRA: Quest of the Jedi', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-thr-09', title: 'The High Republic (2022) #09', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-thr-10', title: 'The High Republic (2022) #10', phase: 'Phase 2', format: 'Comic', read: false },
  { id: 'p2-path-of-vengeance', title: 'Path of Vengeance', phase: 'Phase 2', format: 'YA Novel', read: false },
  { id: 'p3-tales-light-life', title: 'Tales of Light and Life', phase: 'Phase 3', format: 'Anthology', read: false },
  { id: 'p3-shadows-starlight', title: 'Shadows of Starlight', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-eye-of-darkness', title: 'The Eye of Darkness', phase: 'Phase 3', format: 'Adult Novel', read: false },
  { id: 'p3-escape-from-valo', title: 'Escape from Valo', phase: 'Phase 3', format: 'Middle Grade', read: false },
  { id: 'p3-hra-2023-vol-1', title: 'HRA (2023) Volume 1', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-defy-the-storm', title: 'Defy The Storm', phase: 'Phase 3', format: 'YA Novel', read: false },
  { id: 'p3-hra-2023-vol-2', title: 'HRA (2023) Volume 2', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-cc-heir-apparent', title: 'Chronicles Of Corellia: Heir Apparent', phase: 'Phase 3', format: 'Short Story', read: false },
  { id: 'p3-cc-cracking-mask', title: 'Chronicles Of Corellia: Cracking The Mask', phase: 'Phase 3', format: 'Short Story', read: false },
  { id: 'p3-temptation-of-the-force', title: 'Temptation of the Force', phase: 'Phase 3', format: 'Adult Novel', read: false },
  { id: 'p3-thr-p3-vol-1', title: 'THR Phase III Vol. 1: Children of the Storm', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-thr-p3-vol-2', title: 'THR Phase III Vol. 2: The Hunted', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-tears-nameless', title: 'Tears of the Nameless', phase: 'Phase 3', format: 'YA Novel', read: false },
  { id: 'p3-beware-nameless', title: 'Beware the Nameless', phase: 'Phase 3', format: 'Middle Grade', read: false },
  { id: 'p3-hra-echoes-fear', title: 'HRA: Echoes of Fear', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-hra-saber-hire', title: 'HRA: Saber for Hire', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-edge-of-balance-vol-3', title: 'The Edge of Balance: Vol. 3', phase: 'Phase 3', format: 'Manga', read: false },
  { id: 'p3-edge-of-balance-premonition', title: 'The Edge of Balance: Premonition', phase: 'Phase 3', format: 'Manga', read: false },
  { id: 'p3-edge-of-balance-vol-4', title: 'The Edge of Balance, Vol. 4', phase: 'Phase 3', format: 'Manga', read: false },
  { id: 'p3-seeds-starlight', title: 'Seeds of Starlight', phase: 'Phase 3', format: 'Short Story', read: false },
  { id: 'p3-haunted-starlight', title: 'Haunted Starlight', phase: 'Phase 3', format: 'Short Story', read: false },
  { id: 'p3-tempest-breaker', title: 'Tempest Breaker', phase: 'Phase 3', format: 'Audio Drama', read: false },
  { id: 'p3-hra-occlusion-zone', title: 'HRA: Dispatches from the Occlusion Zone', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-hra-crash-zone', title: 'HRA (2023): Crash Zone', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-hra-2023-vol-3', title: 'HRA (2023) Volume 3', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-into-the-light', title: 'Into the Light', phase: 'Phase 3', format: 'YA Novel', read: false },
  { id: 'p3-hra-2023-vol-4', title: 'HRA (2023) Volume 4', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-thr-fear-jedi', title: 'THR: Fear of the Jedi', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-valiant-vow', title: 'A Valiant Vow', phase: 'Phase 3', format: 'Middle Grade', read: false },
  { id: 'p3-trials-jedi', title: 'Trials of the Jedi', phase: 'Phase 3', format: 'Adult Novel', read: false },
  { id: 'p3-hra-2023-vol-5', title: 'HRA (2023) Volume 5', phase: 'Phase 3', format: 'Comic (TPB)', read: false },
  { id: 'p3-toz-fate-eriadu', title: 'Tales From Occlusion Zone: Fate Of Eriadu', phase: 'Phase 3', format: 'Short Story', read: false },
  { id: 'p3-toz-sparks-fly', title: 'Tales From Occlusion Zone: Sparks Fly', phase: 'Phase 3', format: 'Short Story', read: false },
  { id: 'p3-toz-will-fight', title: 'Tales From Occlusion Zone: Will To Fight', phase: 'Phase 3', format: 'Short Story', read: false },
  { id: 'p3-finale-beacon-1', title: 'The Finale: The Beacon #1', phase: 'Phase 3', format: 'Comic', read: false },
  { id: 'p3-acolyte-kelnacca-1', title: 'The Acolyte: Kelnacca #1', phase: 'Phase 3', format: 'Comic', read: false },
  { id: 'p3-acolyte-wayseeker', title: 'The Acolyte: Wayseeker', phase: 'Phase 3', format: 'Adult Novel', read: false },
  { id: 'p3-acolyte-crystal-crown', title: 'The Acolyte: The Crystal Crown', phase: 'Phase 3', format: 'Middle Grade', read: false },
];
